#!/bin/bash -x

#format wywolania skryptu: wyszukaj_poczte uzytkowniksystemu klient_poczty. Np. wyszukaj_poczte admin WLM
#wyszukuje poczte na kazdym koncie uzytkownika

log() { echo $1 >> ${MIEJSCE_ZAPISU}/log.txt && echo $1; }

TM() { echo `date "+%H:%M:%S"`; }

#zabezpieczenie. Jesli za malo parametrow koniec skryptu
[[ "$#" != 2  ]] && { echo "11a) $(TM) - Script started without enough parameters( $1, $2 ). Error"; exit; } || log "11a1) $(TM) Script ran with parameters: $1 , $2 correct " 

WYBRANI_UZYTKOWNICY=$1
MIEJSCE_ZAPISU=$2

# oddzielamy wybrane konta od siebie spacją; np WYBRANI_UZYTKOWNICY=TRUE|admin|sda1 TRUE|uzytkownik2|sda1
for UZYTKOWNIK0 in `echo $WYBRANI_UZYTKOWNICY | awk -F" " '{ print }'`
do
	# oddzielamy wybrane konta od siebie | np na wyjsciu UZYTKOWNIK2=TRUE|admin|sda1
	for UZYTKOWNIK in `echo $UZYTKOWNIK0 | cut -d '|' -f2`
	do
		#po koleji sprawdzamy dla kadego z klientow
		for KLIENT_POCZTY in Outlook WLM Thunderbird
		do 
			log "11b) $(TM) I prepare to search email client ${KLIENT_POCZTY} for user ${UZYTKOWNIK}"
			
			if [[ "$KLIENT_POCZTY" == "Outlook" ]]; then
				SCIEZKA_DO_KATALOGU_KLIENTA="AppData/Local/Microsoft/Outlook"
				#pliki pst porozrzucane sa w roznych miejscach, takze w katalogu Documents dlatego szuka w calym katalogu uzytkownika
				SCIEZKA_DO_PLIKOW=
				CZEGO_SZUKAMY="-name *.pst"
			elif [[ "$KLIENT_POCZTY" == "WLM" ]]; then
				SCIEZKA_DO_KATALOGU_KLIENTA="AppData/Local/Microsoft/Windows Live Mail"
				SCIEZKA_DO_PLIKOW="AppData/Local/Microsoft"
				CZEGO_SZUKAMY="-type d -name Windows\ Live\ Mail"
			elif [[ "$KLIENT_POCZTY" == "Thunderbird" ]]; then
				SCIEZKA_DO_KATALOGU_KLIENTA="AppData/Roaming/Thunderbird/Profiles"
				SCIEZKA_DO_PLIKOW="AppData/Roaming/Thunderbird/Profiles"
				#w tych katalogach jest cala poczta kont imap i pop3	
				CZEGO_SZUKAMY="-type d -name ImapMail -o -name Mail"
			else
				log "11b1) $(TM) - $KLIENT_POCZTY is not suported. Program exit. Error"; exit
			fi

			for PARTYCJA in `cat ${MIEJSCE_ZAPISU}/system_info/partitions_system_win`
			   do
				log "11c) $(TM) - I am looking for ${KLIENT_POCZTY} folders on ${PARTYCJA} in ${UZYTKOWNIK} profile"

				#sprawdzamy czy katalog istnieje
				if [ -d  "/media/${PARTYCJA}/Users/${UZYTKOWNIK}/${SCIEZKA_DO_KATALOGU_KLIENTA}" ];
				  then

					log "11d) $(TM) - I found ${KLIENT_POCZTY} folder in ${UZYTKOWNIK} profile"
		
					#tworzy katalogi z podkatalogami jesli nie ma
					mkdir -p ${MIEJSCE_ZAPISU}/Users/${UZYTKOWNIK}/Mail/${KLIENT_POCZTY} && log "11e) $(TM) - ${KLIENT_POCZTY} Mail folders on destination drive correct. OK" || { TXT="11e1) $(TM) I coud NOT create ${KLIENT_POCZTY} Mail folders on destination drive. Program finished. Error."; log $TXT; yad --title "${NAZWA_PROGRAMU}" --button="gtk-ok:0" --width 300 --text="${TXT}"; exit; } 

					KOMENDA="find /media/${PARTYCJA}/Users/${UZYTKOWNIK}/${SCIEZKA_DO_PLIKOW} ${CZEGO_SZUKAMY}"
		
					#musimy zastosowac eval gdyz bez tego wyszukiwanie katalogowu ze spacjami wywala bledy
					eval $KOMENDA > ${MIEJSCE_ZAPISU}/Users/${UZYTKOWNIK}/Mail/${KLIENT_POCZTY}/tocopy_${KLIENT_POCZTY} && log "11f) $(TM) - I found and saved link to ${KLIENT_POCZTY} archives for ${UZYTKOWNIK} profile" || log "11f1) $(TM) - I can NOT save file with ${KLIENT_POCZTY} archive for ${UZYTKOWNIK} profile. Error"

			 	else 
					log "11c1) $(TM) - I did not find ${KLIENT_POCZTY} folder in ${UZYTKOWNIK} profile"
				fi
			done

		done
	done
done

#musimy sprawdzic co znalazl i wybrac ktore klienty skopiowac
#./dewin_select_client 











